distribution_type: module
generated_by: ExtUtils::MakeMaker version 6.21
abstract:     Parse RCS source control files.
installdirs:  site
license:      perl
name:         Rcs-Parser
version:      VERSIONTAG
version_from: lib/Rcs/Parser.pm
requires:
  Sort::Versions: 0
  Test::Simple: 0
