--- #YAML:1.0
name:               Rcs-Parser
version:            VERSIONTAG
abstract:           Parse and analyze RCS files.
author:
    - Phil Pollard <bennie@cpan.org>
license:            perl_5
distribution_type:  module
configure_requires:
    ExtUtils::MakeMaker:  0
build_requires:
    ExtUtils::MakeMaker:  0
requires:
    Sort::Versions:  0
    Test::Simple:    0
no_index:
    directory:
        - t
        - inc
generated_by:       ExtUtils::MakeMaker version 6.56
meta-spec:
    url:      http://module-build.sourceforge.net/META-spec-v1.4.html
    version:  1.4
